### ISSUE TITLE
Create CVUniverse.cxx

### ISSUE THREAD

**Issue by smgilligan** [MinervaExpt/CCQENu#4]
Having just a CVUniverse.h is bad coding practice. We need a CVUniverse.cxx.

**Comment by smgilligan** [comment]
The branch **cvuniverse_cxx** has been generated off of the most recent **main**, to which the following changes and testing pertains.

* `CVUniverse.cxx` has been created.
* `CVUniverse.h` has been modified into a proper header file.
* `CVUniverse.cxx` has been add to the list of source files in the `CMakeLists.txt` files in folders:
   * `/make_hists/build`
   * `/make_hists/mat`
   * `/make_hists/nonmat` 


`MinervaUniverse.h` and `MinervaUniverse.cxx` were referenced as necessary for the modification or creation of their respective analogous files.

Following these changes the code compiles and has been tested by running `./sidebands AntiNu_v6 10`. Subsequent testing with `./analyze_v5 AntiNu_v6 10` was not completed due to incompatibilities between `AntiNu_v6.json`'s sample handling and relevant recent changes to `/make_hists/include/GetXSec.h`.

**REQUEST**
I would like additional analyzers to test this implementation against their analyses. Please let me know if any issues arise.

**Comment by hschellman** [comment]
The new build is from make_hist/v_08 so that needs to be modded as. well
I probably need to delete build as it is way old and mat will soon be.

On Dec 13, 2021, at 18:25, Sean Gilligan ***@***.***> wrote:

﻿

[This email originated from outside of OSU. Use caution with links and attachments.]

The branch cvuniverse_cxx has been generated off of the most recent main, to which the following changes and testing pertains.

  *   CVUniverse.cxx has been created.
  *   CVUniverse.h has been modified into a proper header file.
  *   CVUniverse.cxx has been add to the list of source files in the CMakeLists.txt files in folders:
     *   /make_hists/build
     *   /make_hists/mat
     *   /make_hists/nonmat

MinervaUniverse.h and MinervaUniverse.cxx were referenced as necessary for the modification or creation of their respective analogous files.

Following these changes the code compiles and has been tested by running ./sidebands AntiNu_v6 10. Subsequent testing with ./analyze_v5 AntiNu_v6 10 was not completed due to incompatibilities between AntiNu_v6.json's sample handling and relevant recent changes to /make_hists/include/GetXSec.h.

REQUEST
I would like additional analyzers to test this implementation against their analyses. Please let me know if any issues arise.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMinervaExpt%2FCCQENu%2Fissues%2F4%23issuecomment-993095498&data=04%7C01%7Cheidi.schellman%40oregonstate.edu%7Cce24525acaf84114850e08d9bea8f46a%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637750455135287054%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=G8k0Adn9TTCuDPvp%2ByjhmVVyGcVAfjAA0kHDbsO90es%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIA37DIRWHHTW5DTM6GIMDDUQ2TINANCNFSM5J2HSMVA&data=04%7C01%7Cheidi.schellman%40oregonstate.edu%7Cce24525acaf84114850e08d9bea8f46a%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637750455135297009%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=N2zGsDJpTZZq9Y%2BZQtdumKHc6p0HnmKmumIVIcScZEg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cheidi.schellman%40oregonstate.edu%7Cce24525acaf84114850e08d9bea8f46a%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637750455135297009%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pEfnj12o9D%2FaJQNiqAxBGiKqFm2DQ0Ci5l7n8RI3X7g%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cheidi.schellman%40oregonstate.edu%7Cce24525acaf84114850e08d9bea8f46a%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637750455135306966%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=eYxV5iElYZq7AcKuKp78ihVBnLGKQIjRVaI%2FkORSzsU%3D&reserved=0>.

**Comment by smgilligan** [comment]
`CVUniverse.cxx` has been add to the list of source files in `/make_hists/v_08/CMakeLists.txt`. I should have performed a better search for cmake files. My mistake.

**Comment by hschellman** [comment]
I committed the CMakeLists.cxx to the main branch

**Comment by smgilligan** [comment]
This was finished back in December. Closing issue.
